#!/bin/sh
#
# @name LQR Controller Quad
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @maintainer Patrick Thomas <thomaspj1017@vt.edu>

. ${R}etc/init.d/rc.x_quad_defaults

set MIXER x_quad
