#!/bin/sh
#
# @name OmniCopter
#
# @type Airship
# @class Airship
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
#
# @maintainer Patrick Thomas <thomaspj1017@vt.edu>


. ${R}etc/init.d/rc.omni_defaults

# Motor control parameters
param set PWM_MAIN_MAX 2000
param set PWM_MAIN_MIN 1000
param set PWM_MAIN_RATE 0
param set PWM_MAIN_OUT 12345678

param set PWM_MAIN_DIS1 1500
param set PWM_MAIN_FAIL1 1500
param set PWM_MAIN_DIS2 1500
param set PWM_MAIN_FAIL2 1500
param set PWM_MAIN_DIS3 1500
param set PWM_MAIN_FAIL3 1500
param set PWM_MAIN_DIS4 1500
param set PWM_MAIN_FAIL4 1500
param set PWM_MAIN_DIS5 1500
param set PWM_MAIN_FAIL5 1500
param set PWM_MAIN_DIS6 1500
param set PWM_MAIN_FAIL6 1500
param set PWM_MAIN_DIS7 1500
param set PWM_MAIN_FAIL7 1500
param set PWM_MAIN_DIS8 1500
param set PWM_MAIN_FAIL8 1500

param set GPS_UBX_DYNMODEL 6

# External Vision (Optitrack) Parameters
param set EKF2_AID_MASK 24
param set EKF2_HGT_MODE 3
param set EKF2_EV_DELAY 18
param set EKF2_EVP_NOISE 0.005
param set EKF2_IMU_POS_Z -0.035
param set IMU_GYRO_CUTOFF 30

# Offboard serial communication parameters
param set SER_TEL1_BAUD 921600
param set MAV_0_CONFIG 101
param set MAV_0_MODE 0
param set MAV_0_RATE 46000

# SD Logging
param set SDLOG_UTC_OFFSET -360

# Battery Parameters
param set BAT_N_CELLS 4
param set BAT1_A_PER_V 36.3675
param set BAT1_V_DIV 18.1820

# Radio Parameters
param set COM_ARM_SWISBTN 0
# param set RC_MAP_ARM_SW 7
param set COM_RC_ARM_HYST 150
param set COM_RCL_EXCEPT 4 	# Needed for offboard mode
param set COM_RC_IN_MODE 0
param set COM_RC_LOSS_T 35

# Offboard flying parameters (disabling failsafes)
param set COM_DISARM_LAND -1 	# Disable commander auto disarm on landing to prevent false disarm
param set COM_DISARM_PRFLT -1 	# Disable commander auto disarm after not taking off to prevent false disarm
param set COM_OF_LOSS_T 60
param set COM_OBL_ACT -1
param set NAV_RCL_ACT 0
param set NAV_DLL_ACT 0
param set NAV_ACC_RAD 2

set MIXER omni
